### ISSUE TITLE
500 Error on Accessing /api/info/aggregates via Swagger

### ISSUE THREAD

**Issue by MOTOO11** [J-Tech-Japan/Sekiban#162]
Upon launching the "BookBorrowing.Web.Cosmos" sample project and attempting to access the "/api/info/aggregates" endpoint through Swagger, a 500 Internal Server Error occurred.

![image](https://github.com/J-Tech-Japan/Sekiban/assets/2063244/c4f08a23-8816-4040-9b91-3206a3f15cc7)

# Reproduction Steps

1. Launch the "BookBorrowing.Web.Cosmos" sample project.
2. Access Swagger UI.
3. Navigate to the "/api/info/aggregates" endpoint.
4. Observe the 500 Internal Server Error.

**Comment by tomohisa** [comment]
Thank you! I will check it out if it is the issue of the usage or the framework.

**Comment by MOTOO11** [comment]
```
 "Object of type 'System.String' cannot be converted to type 'System.Collections.Generic.IEnumerable`1[System.ComponentModel.DataAnnotations.ValidationResult]'."
```

In `SekibanApiListController.cs`,
I am attempting to create a `CommandExecutorResponse`  using reflection.
However, a string type is being passed to the constructor's `IEnumerable<ValidationResult>? ValidationResults`.

``` cs
public record CommandExecutorResponse(
    Guid? AggregateId,
    Guid? CommandId,
    int Version,
    IEnumerable<ValidationResult>? ValidationResults,
    string? LastSortableUniqueId,
    string AggregatePayloadOutTypeName,
    int EventCount);
```

![image](https://github.com/J-Tech-Japan/Sekiban/assets/2063244/fe96b1dd-b8e0-4981-a112-335c8fcc90e0)
