### ISSUE TITLE
Refactoring following IntelliCode suggestions

### ISSUE THREAD

**Issue by tkawae** [J-Tech-Japan/Sekiban#206]
**Is your feature request related to a problem? Please describe.**
When viewing Sekiban code in Visual Studio, the IntelliCode feature displays several suggestions for code improvement. The following points may improve performance at runtime or readability of the code.

1. Mark methods as static if it does not access instance data.
2. Use `List<T>.Count != 0` instead of `List<T>.Any()`.
3. Null check can be simplified (IDE0270).

**Describe the solution you'd like**
It is recommended to modify the code according to the suggestion.

**Comment by tomohisa** [comment]
Sounds good. Please implement.
